# Generated by Django 4.2.30 on 2026-07-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField()),
                ('url', models.URLField(help_text='Link to the full article (e.g. Medium, Dev.to)')),
                ('published_date', models.DateField()),
                ('read_time', models.CharField(default='5 min read', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='e.g. Bachelor of Engineering (BE)', max_length=150)),
                ('field_of_study', models.CharField(help_text='e.g. Computer Science', max_length=150)),
                ('institution', models.CharField(max_length=200)),
                ('start_year', models.CharField(max_length=20)),
                ('end_year', models.CharField(max_length=20)),
                ('grade', models.CharField(blank=True, help_text='e.g. CGPA: 8.4 / 10', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('start_date', models.CharField(help_text='e.g. Mar 2026', max_length=50)),
                ('end_date', models.CharField(help_text='e.g. June 2026 or Present', max_length=50)),
                ('description', models.TextField(help_text='Newline separated bullet points')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('icon_class', models.CharField(default='fas fa-code', max_length=50)),
                ('icon_color', models.CharField(default='#6366f1', help_text='Hex color code (e.g. #6366f1)', max_length=20)),
                ('github_link', models.URLField(blank=True)),
                ('demo_link', models.URLField(blank=True)),
                ('features', models.TextField(blank=True, help_text='Comma-separated features')),
                ('tech_stack', models.TextField(blank=True, help_text='Comma-separated technologies')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(default='Nandini Y. | Python Full Stack Developer', max_length=150)),
                ('seo_description', models.TextField(default='Python Full Stack Developer specializing in Django, React, MySQL, and REST APIs.')),
                ('seo_keywords', models.TextField(default='Python developer, Full Stack Developer, Django, React, MySQL, portfolio, Nandini')),
                ('seo_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('google_analytics_id', models.CharField(blank=True, help_text='e.g. G-XXXXXXXXXX', max_length=50)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(help_text='e.g. Programming Languages, Frontend, Backend, Tools', max_length=100)),
                ('percentage', models.IntegerField(default=0)),
                ('icon_class', models.CharField(default='fas fa-code', help_text='FontAwesome class e.g. fab fa-python', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
