# Generated by Django 6.0.7 on 2026-07-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_article_education_experience_project_sitesettings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category_order', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='skill',
            name='category_order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first (e.g. 1 for Frontend, 2 for Backend)'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0, help_text='Order of this skill within its category'),
        ),
    ]
