# Generated by Django 6.0.7 on 2026-07-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_skill_options_skill_category_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category_order', 'category', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='skill',
            name='icon_color',
            field=models.CharField(default='#06b6d4', help_text='Hex color code (e.g. #f0db4f for JS)', max_length=20),
        ),
    ]
