# Generated by Django 6.0.7 on 2026-07-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_skill_options_skill_icon_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(default='devicon-python-plain colored', help_text='Devicon or FontAwesome class e.g. devicon-python-plain colored', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_color',
            field=models.CharField(blank=True, default='', help_text='Leave blank for original icon colors. Or use hex code (e.g. #f0db4f)', max_length=20),
        ),
    ]
