# Generated by Django 6.0.7 on 2026-07-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_skill_icon_class_alter_skill_icon_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='icon_class',
            field=models.CharField(default='fas fa-graduation-cap', help_text='FontAwesome class e.g. fas fa-school', max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='category_icon_class',
            field=models.CharField(default='fas fa-layer-group', help_text='FontAwesome class for the category', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(default='fas fa-code', help_text='FontAwesome class e.g. fab fa-python', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_color',
            field=models.CharField(default='#06b6d4', help_text='Hex color code (e.g. #f0db4f for JS)', max_length=20),
        ),
    ]
