# Generated by Django 6.0.7 on 2026-07-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_education_icon_class_skill_category_icon_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='grade_type',
            field=models.CharField(blank=True, choices=[('CGPA', 'CGPA'), ('Percentage', 'Percentage'), ('', 'None')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.CharField(blank=True, help_text='e.g. 8.4 or 77', max_length=100),
        ),
    ]
