# Generated by Django 6.0.7 on 2026-07-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_education_grade_type_alter_education_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='icon_class',
            field=models.CharField(default='fas fa-laptop-code', help_text='FontAwesome class e.g. fas fa-briefcase', max_length=50),
        ),
    ]
