# Generated by Django 6.0.7 on 2026-07-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_project_demo_link_alter_project_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(help_text='e.g. Certification, Internship Certificate', max_length=150)),
                ('institution', models.CharField(help_text='e.g. NIIT / Udemy', max_length=200)),
                ('duration', models.CharField(help_text='e.g. 6 Months · 2025', max_length=100)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(blank=True, help_text='Comma-separated technologies', max_length=250)),
                ('icon_class', models.CharField(default='fas fa-certificate', max_length=50)),
                ('color_start', models.CharField(default='#6366f1', help_text='Hex code, e.g. #6366f1', max_length=20)),
                ('color_end', models.CharField(default='#8b5cf6', help_text='Hex code, e.g. #8b5cf6', max_length=20)),
                ('text_color_class', models.CharField(default='text-primary-400', help_text='Tailwind class, e.g. text-primary-400', max_length=50)),
                ('url', models.URLField(blank=True, help_text='Link to the certificate')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='features',
            field=models.TextField(blank=True, help_text='Newline-separated features'),
        ),
    ]
