# Generated by Django 6.0.7 on 2026-07-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_certificate_alter_project_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='url',
        ),
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload certificate image', null=True, upload_to='certificates/'),
        ),
    ]
