# Generated by Django 6.0.7 on 2026-09-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Your main profile image (for the hero section)', null=True, upload_to='profile/'),
        ),
    ]
